# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
        environment:
          APP_SETTINGS: project.config.TestingConfig
          DATABASE_TEST_URL: postgres://postgres@localhost:5432/base_backend_test
          SECRET_KEY: my_secret

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: base_backend_test
          POSTGRES_PASSWORD: postgres

    working_directory: ~/flask-base-api

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-


      - run:
          name: coverage package
          command: |
            sudo apt-get update
            sudo apt-get install python3-dev gcc

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            sudo pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Before Script
          command: |
            python manage.py recreate_db

      # run tests!
      - run:
          name: run tests
          command: |
            python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
